sonar.projectKey=smartgarden
sonar.sources=.
# Exclude virtualenvs, site-packages and migrations from analysis
sonar.exclusions=**/.venv/**,**/venv/**,**/*site-packages/**,**/migrations/**,**/node_modules/**
