# Generated by Django 6.0 on 2025-12-29 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Garden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('device_type', models.CharField(choices=[('AHOPEGARDEN_12', 'Ahopegarden 12 Pod')], default='AHOPEGARDEN_12', max_length=40)),
                ('is_public', models.BooleanField(default=False)),
                ('share_slug', models.SlugField(blank=True, max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gardens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('plant_name', models.CharField(blank=True, max_length=120)),
                ('planted_at', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('EMPTY', 'Empty'), ('SEEDED', 'Seeded'), ('SPROUTED', 'Sprouted'), ('GROWING', 'Growing'), ('HARVESTING', 'Harvesting'), ('REMOVED', 'Removed')], default='EMPTY', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('garden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pods', to='gardens.garden')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('garden', 'position')},
            },
        ),
        migrations.CreateModel(
            name='PodNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='pod_photos/')),
                ('pod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='gardens.pod')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
