# Generated by Django 6.0 on 2025-12-29 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0002_garden_guest_token_garden_is_guest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garden',
            name='share_slug',
            field=models.SlugField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
