# Generated by Django 6.0 on 2025-12-29 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0003_alter_garden_share_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='garden',
            name='view_front',
            field=models.CharField(choices=[('bottom', 'Bottom'), ('top', 'Top')], default='bottom', max_length=10),
        ),
    ]
