# Generated by Django 6.0 on 2025-12-29 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0004_garden_view_front'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garden',
            name='view_front',
            field=models.CharField(choices=[('left', 'Left'), ('right', 'Right')], default='left', max_length=10),
        ),
    ]
